const {
  ONBOARD_SERVICE_URL,
  AUTH_SERVICE_URL,
  ONBOARD_QUERY_SERVICE_URL,
  CATALOG_SERVICE_URL,
  CATALOG_QUERY_SERVICE_URL,
  SYNC_COMMAND_SERVICE_URL,
  SYNC_QUERY_SERVICE_URL,
  CATALOG_NEW_SERVICE_URL,
  PIMSESSION,
  PIM_COOKIE_PASSWORD,
  PIMSESSION_TIMEOUT,
} = process.env;

module.exports = {
  reactStrictMode: true,
  env: {
    ONBOARD_SERVICE_URL,
    AUTH_SERVICE_URL,
    ONBOARD_QUERY_SERVICE_URL,
    CATALOG_SERVICE_URL,
    CATALOG_QUERY_SERVICE_URL,
    SYNC_COMMAND_SERVICE_URL,
    SYNC_QUERY_SERVICE_URL,
    CATALOG_NEW_SERVICE_URL,
    PIMSESSION,
    PIM_COOKIE_PASSWORD,
    PIMSESSION_TIMEOUT,
  },
  images: {
    domains: ["ri-brands-pim.s3.ap-south-1.amazonaws.com"],
  },
};
