//onboard-apis
export const CREATE_BRAND_DATA_LOADING = "CREATE_BRAND_DATA_LOADING";
export const CREATE_BRAND_DATA_SUCCESS = "CREATE_BRAND_DATA_SUCCESS";
export const CREATE_BRAND_DATA_FAILURE = "CREATE_BRAND_DATA_FAILURE";

export const GET_BRAND_DATA_LOADING = "GET_BRAND_DATA_LOADING";
export const GET_BRAND_DATA_SUCCESS = "GET_BRAND_DATA_SUCCESS";
export const GET_BRAND_DATA_FAILURE = "GET_BRAND_DATA_FAILURE";

export const UPDATE_BRAND_DATA_LOADING = "UPDATE_BRAND_DATA_LOADING";
export const UPDATE_BRAND_DATA_SUCCESS = "UPDATE_BRAND_DATA_SUCCESS";
export const UPDATE_BRAND_DATA_FAILURE = "UPDATE_BRAND_DATA_FAILURE";
//auth-apis
export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_LOGIN_AT = "USER_LOGIN_AT";
export const USER_LOGIN_RT = "USER_LOGIN_RT";

export const GET_USER_BY_ID_LOADING = "GET_USER_BY_ID_LOADING";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";
export const GET_USER_BY_ID_FAILURE = "GET_USER_BY_ID_FAILURE";

export const UPDATE_USER_DATA_LOADING = "UPDATE_USER_DATA_LOADING";
export const UPDATE_USER_DATA_SUCCESS = "UPDATE_USER_DATA_SUCCESS";
export const UPDATE_USER_DATA_FAILURE = "UPDATE_USER_DATA_FAILURE";

export const FILTER_USER_LOADING = "FILTER_USER_LOADING";
export const FILTER_USER_SUCCESS = "FILTER_USER_SUCCESS";
export const FILTER_USER_FAILURE = "FILTER_USER_FAILURE";

//onboard query -apis
export const GET_CHANNELS_DATA_LOADING = "GET_CHANNELS_DATA_LOADING";
export const GET_CHANNELS_DATA_SUCCESS = "GET_CHANNELS_DATA_SUCCESS";
export const GET_CHANNELS_DATA_FAILURE = "GET_CHANNELS_DATA_FAILURE";

export const GET_COUNTRY_DATA_LOADING = "GET_COUNTRY_DATA_LOADING";
export const GET_COUNTRY_DATA_SUCCESS = "GET_COUNTRY_DATA_SUCCESS";
export const GET_COUNTRY_DATA_FAILURE = "GET_COUNTRY_DATA_FAILURE";

export const GET_MARKETPLACE_DATA_LOADING = "GET_MARKETPLACE_DATA_LOADING";
export const GET_MARKETPLACE_DATA_SUCCESS = "GET_MARKETPLACE_DATA_SUCCESS";
export const GET_MARKETPLACE_DATA_FAILURE = "GET_MARKETPLACE_DATA_FAILURE";

export const GET_CHANNEL_BYID_DATA_LOADING = "GET_CHANNEL_BYID_DATA_LOADING";
export const GET_CHANNEL_BYID_DATA_SUCCESS = "GET_CHANNEL_BYID_DATA_SUCCESS";
export const GET_CHANNEL_BYID_DATA_FAILURE = "GET_CHANNEL_BYID_DATA_FAILURE";

export const GET_BRAND_BYID_DATA_LOADING = "GET_BRAND_BYID_DATA_LOADING";
export const GET_BRAND_BYID_DATA_SUCCESS = "GET_BRAND_BYID_DATA_SUCCESS";
export const GET_BRAND_BYID_DATA_FAILURE = "GET_BRAND_BYID_DATA_FAILURE";

export const CREATE_CHANNEL_DATA_LOADING = "CREATE_CHANNEL_DATA_LOADING";
export const CREATE_CHANNEL_DATA_SUCCESS = "CREATE_CHANNEL_DATA_SUCCESS";
export const CREATE_CHANNEL_DATA_FAILURE = "CREATE_CHANNEL_DATA_FAILURE";

export const GET_CHANNEL_DATA_LOADING = "GET_CHANNEL_DATA_LOADING";
export const GET_CHANNEL_DATA_SUCCESS = "GET_CHANNEL_DATA_SUCCESS";
export const GET_CHANNEL_DATA_FAILURE = "GET_CHANNEL_DATA_FAILURE";

export const UPDATE_CHANNEL_DATA_LOADING = "UPDATE_CHANNEL_DATA_LOADING";
export const UPDATE_CHANNEL_DATA_SUCCESS = "UPDATE_CHANNEL_DATA_SUCCESS";
export const UPDATE_CHANNEL_DATA_FAILURE = "UPDATE_CHANNEL_DATA_FAILURE";

export const GET_BRAND_DROPDOWN_DATA_LOADING =
  "GET_BRAND_DROPDOWN_DATA_LOADING";
export const GET_BRAND_DROPDOWN_DATA_SUCCESS =
  "GET_BRAND_DROPDOWN_DATA_SUCCESS";
export const GET_BRAND_DROPDOWN_DATA_FAILURE =
  "GET_BRAND_DROPDOWN_DATA_FAILURE";

export const GET_CHANNEL_ATTRIBUTE_LOADING = "GET_CHANNEL_ATTRIBUTE_LOADING";
export const GET_CHANNEL_ATTRIBUTE_SUCCESS = "GET_CHANNEL_ATTRIBUTE_SUCCESS";
export const GET_CHANNEL_ATTRIBUTE_FAILURE = "GET_CHANNEL_ATTRIBUTE_FAILURE";

export const CHANNEL_MAPPING_LOADING = "CHANNEL_MAPPING_LOADING";
export const CHANNEL_MAPPING_SUCCESS = "CHANNEL_MAPPING_SUCCESS";
export const CHANNEL_MAPPING_FAILURE = "CHANNEL_MAPPING_FAILURE";

// CATEGORY  catalog-command-handler
export const CREATE_CATEGORY_DATA_LOADING = "CREATE_CATEGORY_DATA_LOADING";
export const CREATE_CATEGORY_DATA_SUCCESS = "CREATE_CATEGORY_DATA_SUCCESS";
export const CREATE_CATEGORY_DATA_FAILURE = "CREATE_CATEGORY_DATA_FAILURE";

export const UPDATE_CATEGORY_DATA_LOADING = "UPDATE_CATEGORY_DATA_LOADING";
export const UPDATE_CATEGORY_DATA_SUCCESS = "UPDATE_CATEGORY_DATA_SUCCESS";
export const UPDATE_CATEGORY_DATA_FAILURE = "UPDATE_CATEGORY_DATA_FAILURE";

export const ATTRIBUTE_UPDATE_GROUP_BY_ID_DATA_LOADING =
  "ATTRIBUTE_UPDATE_GROUP_BY_ID_DATA_LOADING";
export const ATTRIBUTE_UPDATE_GROUP_BY_ID_DATA_SUCCESS =
  "ATTRIBUTE_UPDATE_GROUP_BY_ID_DATA_SUCCESS";
export const ATTRIBUTE_UPDATE_GROUP_BY_ID_DATA_FAILURE =
  "ATTRIBUTE_UPDATE_GROUP_BY_ID_DATA_FAILURE";

export const CREATE_GROUP_DATA_LOADING = "CREATE_GROUP_DATA_LOADING";
export const CREATE_GROUP_DATA_SUCCESS = "CREATE_GROUP_DATA_SUCCESS";
export const CREATE_GROUP_DATA_FAILURE = "CREATE_GROUP_DATA_FAILURE";

export const SET_EMAIL = "SET_EMAIL";
export const USER_DETAILS = "USER_DETAILS";
export const USER_BRAND = "USER_BRAND";

export const USER_EMAIL = "USER_EMAIL";

export const USER_ROLE = "USER_ROLE";

export const INIT_APP_SUCCESS = "INIT_APP_SUCCESS";
export const INIT_APP_FAILURE = "INIT_APP_FAILURE";

//get catalog - query
export const GET_ALL_PRODUCT_DATA_LOADING = "GET_ALL_PRODUCT_DATA_LOADING";
export const GET_ALL_PRODUCT_DATA_SUCCESS = "GET_ALL_PRODUCT_DATA_SUCCESS";
export const GET_ALL_PRODUCT_DATA_FAILURE = "GET_ALL_PRODUCT_DATA_FAILURE";

export const GET_ATTRIBUTES_DATA_LOADING = "GET_ATTRIBUTES_DATA_LOADING";
export const GET_ATTRIBUTES_DATA_SUCCESS = "GET_ATTRIBUTES_DATA_SUCCESS";
export const GET_ATTRIBUTES_DATA_FAILURE = "GET_ATTRIBUTES_DATA_FAILURE";

export const GET_CATEGORIES_DATA_LOADING = "GET_CATEGORIES_DATA_LOADING";
export const GET_CATEGORIES_DATA_SUCCESS = "GET_CATEGORIES_DATA_SUCCESS";
export const GET_CATEGORIES_DATA_FAILURE = "GET_CATEGORIES_DATA_FAILURE";

export const ADD_CATEGORY_LOADING = "ADD_CATEGORY_LOADING";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE";

export const GET_ATTRIBUTES_BYID_DATA_LOADING =
  "GET_ATTRIBUTES_BYID_DATA_LOADING";
export const GET_ATTRIBUTES_BYID_DATA_SUCCESS =
  "GET_ATTRIBUTES_BYID_DATA_SUCCESS";
export const GET_ATTRIBUTES_BYID_DATA_FAILURE =
  "GET_ATTRIBUTES_BYID_DATA_FAILURE";

export const GET_ATTRIBUTES_GROUP_DATA_LOADING =
  "GET_ATTRIBUTES_GROUP_DATA_LOADING";
export const GET_ATTRIBUTES_GROUP_DATA_SUCCESS =
  "GET_ATTRIBUTES_GROUP_DATA_SUCCESS";
export const GET_ATTRIBUTES_GROUP_DATA_FAILURE =
  "GET_ATTRIBUTES_GROUP_DATA_FAILURE";

export const GET_PRODUCT_PIM_MODEL_CODE_LOADING =
  "GET_PRODUCT_PIM_MODEL_CODE_LOADING";
export const GET_PRODUCT_PIM_MODEL_CODE_SUCCESS =
  "GET_PRODUCT_PIM_MODEL_CODE_SUCCESS";
export const GET_PRODUCT_PIM_MODEL_CODE_FAILURE =
  "GET_PRODUCT_PIM_MODEL_CODE_FAILURE";

export const CREATE_BULK_DATA_LOADING = "CREATE_BULK_DATA_LOADING";
export const CREATE_BULK_DATA_SUCCESS = "CREATE_BULK_DATA_SUCCESS";
export const CREATE_BULK_DATA_FAILURE = "CREATE_BULK_DATA_FAILURE";

export const BULK_LISTING_DATA_LOADING = "BULK_LISTING_DATA_LOADING";
export const BULK_LISTING_DATA_SUCCESS = "BULK_LISTING_DATA_SUCCESS";
export const BULK_LISTING_DATA_FAILURE = "BULK_LISTING_DATA_FAILURE";

export const ATTRIBUTE_CREATE_GROUP_BY_ID_DATA_LOADING =
  "ATTRIBUTE_CREATE_GROUP_BY_ID_DATA_LOADING";
export const ATTRIBUTE_CREATE_GROUP_BY_ID_DATA_SUCCESS =
  "ATTRIBUTE_CREATE_GROUP_BY_ID_DATA_SUCCESS";
export const ATTRIBUTE_CREATE_GROUP_BY_ID_DATA_FAILURE =
  "ATTRIBUTE_CREATE_GROUP_BY_ID_DATA_FAILURE";

export const GET_USER_LIST_DATA_LOADING = "GET_USER_LIST_DATA_LOADING";
export const GET_USER_LIST_DATA_SUCCESS = "GET_USER_LIST_DATA_SUCCESS";
export const GET_USER_LIST_DATA_FAILURE = "GET_USER_LIST_DATA_FAILURE";

export const GET_ROLE_DATA_LOADING = "GET_ROLE_DATA_LOADING";
export const GET_ROLE_DATA_SUCCESS = "GET_ROLE_DATA_SUCCESS";
export const GET_ROLE_DATA_FAILURE = "GET_ROLE_DATA_FAILURE";

export const CREATE_USER_DATA_LOADING = "CREATE_USER_DATA_LOADING";
export const CREATE_USER_DATA_SUCCESS = "CREATE_USER_DATA_SUCCESS";
export const CREATE_USER_DATA_FAILURE = "CREATE_USER_DATA_FAILURE";

export const GET_TEMPLATE_DATA_LOADING = "GET_TEMPLATE_DATA_LOADING";
export const GET_TEMPLATE_DATA_SUCCESS = "GET_TEMPLATE_DATA_SUCCESS";
export const GET_TEMPLATE_DATA_FAILURE = "GET_TEMPLATE_DATA_FAILURE";

export const ATTRIBUTE_LIST_LOADING = "ATTRIBUTE_LIST_LOADING";
export const ATTRIBUTE_LIST_SUCCESS = "ATTRIBUTE_LIST_SUCCESS";
export const ATTRIBUTE_LIST_FAILURE = "ATTRIBUTE_LIST_FAILURE";

export const CATEGORY_DROPDOWN_LIST_LOADING = "CATEGORY_DROPDOWN_LIST_LOADING";
export const CATEGORY_DROPDOWN_LIST_SUCCESS = "CATEGORY_DROPDOWN_LIST_SUCCESS";
export const CATEGORY_DROPDOWN_LIST_FAILURE = "CATEGORY_DROPDOWN_LIST_FAILURE";

export const GET_CHANNEL_ATTRIBUTE = "GET_CHANNEL_ATTRIBUTE";

export const GET_ALL_PRODUCT_LIST_LOADING = "GET_ALL_PRODUCT_LIST_LOADING";
export const GET_ALL_PRODUCT_LIST_SUCCESS = "GET_ALL_PRODUCT_LIST_SUCCESS";
export const GET_ALL_PRODUCT_LIST_FAILURE = "GET_ALL_PRODUCT_LIST_FAILURE";

export const BULK_UPLOAD_LOADING = "BULK_UPLOAD_LOADING";
export const BULK_UPLOAD_SUCCESS = "BULK_UPLOAD_SUCCESS";
export const BULK_UPLOAD_FAILURE = "BULK_UPLOAD_FAILURE";

export const GET_PRODUCT_DETAILS_LOADING = "GET_PRODUCT_DETAILS_LOADING";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAILURE = "GET_PRODUCT_DETAILS_FAILURE";

export const GET_ROLES_PRIVILEGE_LOADING = "GET_ROLES_PRIVILEGE_LOADING";
export const GET_ROLES_PRIVILEGE_SUCCESS = "GET_ROLES_PRIVILEGE_SUCCESS";
export const GET_ROLES_PRIVILEGE_FAILURE = "GET_ROLES_PRIVILEGE_FAILURE";

export const CREATE_ATTRIBUTE_SET_LOADING = "CREATE_ATTRIBUTE_SET_LOADING";
export const CREATE_ATTRIBUTE_SET_SUCCESS = "CREATE_ATTRIBUTE_SET_SUCCESS";
export const CREATE_ATTRIBUTE_SET_FAILURE = "CREATE_ATTRIBUTE_SET_FAILURE";

export const REVALIDATE_DATA_LOADING = "REVALIDATE_DATA_LOADING";
export const REVALIDATE_DATA_SUCCESS = "REVALIDATE_DATA_SUCCESS";
export const REVALIDATE_DATA_FAILURE = "REVALIDATE_DATA_FAILURE";

export const STATUS_DATA_LOADING = "STATUS_DATA_LOADING";
export const STATUS_DATA_SUCCESS = "STATUS_DATA_SUCCESS";
export const STATUS_DATA_FAILURE = "STATUS_DATA_FAILURE";

export const GET_ACTIVE_PRODUCT_LIST_LOADING =
  "GET_ACTIVE_PRODUCT_LIST_LOADING";
export const GET_ACTIVE_PRODUCT_LIST_SUCCESS =
  "GET_ACTIVE_PRODUCT_LIST_SUCCESS";
export const GET_ACTIVE_PRODUCT_LIST_FAILURE =
  "GET_ACTIVE_PRODUCT_LIST_FAILURE";

export const PUBLISH_CATALOG_REQUEST = "PUBLISH_CATALOG_REQUEST";
export const PUBLISH_CATALOG_SUCCESS = "PUBLISH_CATALOG_SUCCESS";
export const PUBLISH_CATALOG_FAILURE = "PUBLISH_CATALOG_FAILURE";
export const PRODUCT_UPDATE_DATA_LOADING = "PRODUCT_UPDATE_DATA_LOADING";
export const PRODUCT_UPDATE_DATA_SUCCESS = "PRODUCT_UPDATE_DATA_SUCCESS";
export const PRODUCT_UPDATE_DATA_FAILURE = "PRODUCT_UPDATE_DATA_FAILURE";

export const CREATE_CHANNEL_ATTRIBUT_DATA_LOADING =
  "CREATE_CHANNEL_ATTRIBUT_DATA_LOADING";
export const CREATE_CHANNEL_ATTRIBUT_DATA_SUCCESS =
  "CREATE_CHANNEL_ATTRIBUT_DATA_SUCCESS";
export const CREATE_CHANNEL_ATTRIBUTE_DATA_FAILURE =
  "CREATE_CHANNEL_ATTRIBUTE_DATA_FAILURE";

export const MY_PROFILE_DATA_LOADING = "MY_PROFILE_DATA_LOADING";
export const MY_PROFILE_DATA_SUCCESS = "MY_PROFILE_DATA_SUCCESS";
export const MY_PROFILE_DATA_FAILURE = "MY_PROFILE_DATA_FAILURE";

export const ATTRIBUTE_SET_DETAILS_DATA_LOADING =
  "ATTRIBUTE_SET_DETAILS_DATA_LOADING";
export const ATTRIBUTE_SET_DETAILS_DATA_SUCCESS =
  "ATTRIBUTE_SET_DETAILS_DATA_SUCCESS";
export const ATTRIBUTE_SET_DETAILS_DATA_FAILURE =
  "ATTRIBUTE_SET_DETAILS_DATA_FAILURE";

export const BULK_LIST_DATA_LOADING = "BULK_LIST_DATA_LOADING";
export const BULK_LIST_DATA_SUCCESS = "BULK_LIST_DATA_SUCCESS";
export const BULK_LIST_DATA_FAILURE = "BULK_LIST_DATA_FAILURE";

// master attributes add
export const ADD_MASTER_ATTRIBUTE_LOADING = "ADD_MASTER_ATTRIBUTE_LOADING";
export const ADD_MASTER_ATTRIBUTE_SUCCESS = "ADD_MASTER_ATTRIBUTE_SUCCESS";
export const ADD_MASTER_ATTRIBUTE_FAILURE = "ADD_MASTER_ATTRIBUTE_FAILURE";

export const NOTIFICATION_DATA_LOADING = "NOTIFICATION_DATA_LOADING";
export const NOTIFICATION_DATA_SUCCESS = "NOTIFICATION_DATA_SUCCESS";
export const NOTIFICATION_DATA_FAILURE = "NOTIFICATION_DATA_FAILURE";

export const MEDIA_LISTING_LOADING = "MEDIA_LISTING_LOADING";
export const MEDIA_LISTING_SUCCESS = "MEDIA_LISTING_SUCCESS";
export const MEDIA_LISTING_FAILURE = "MEDIA_LISTING_FAILURE";

export const GET_CATEGORIES_LIST_DATA_LOADING =
  "GET_CATEGORIES_LIST_DATA_LOADING";
export const GET_CATEGORIES_LIST_DATA_SUCCESS =
  "GET_CATEGORIES_LIST_DATA_SUCCESS";
export const GET_CATEGORIES_LIST_DATA_FAILURE =
  "GET_CATEGORIES_LIST_DATA_FAILURE";
