
//onboard-apis
export const CREATE_BRAND_DATA_LOADING = "CREATE_BRAND_DATA_LOADING";
export const CREATE_BRAND_DATA_SUCCESS = "CREATE_BRAND_DATA_SUCCESS";
export const CREATE_BRAND_DATA_FAILURE = "CREATE_BRAND_DATA_FAILURE";

export const GET_BRAND_DATA_LOADING = "GET_BRAND_DATA_LOADING";
export const GET_BRAND_DATA_SUCCESS = "GET_BRAND_DATA_SUCCESS";
export const GET_BRAND_DATA_FAILURE = "GET_BRAND_DATA_FAILURE";
