//onboard-apis
export const CREATE_BRAND_DATA_LOADING = "CREATE_BRAND_DATA_LOADING";
export const CREATE_BRAND_DATA_SUCCESS = "CREATE_BRAND_DATA_SUCCESS";
export const CREATE_BRAND_DATA_FAILURE = "CREATE_BRAND_DATA_FAILURE";

export const GET_BRAND_DATA_LOADING = "GET_BRAND_DATA_LOADING";
export const GET_BRAND_DATA_SUCCESS = "GET_BRAND_DATA_SUCCESS";
export const GET_BRAND_DATA_FAILURE = "GET_BRAND_DATA_FAILURE";

export const UPDATE_BRAND_DATA_LOADING = "UPDATE_BRAND_DATA_LOADING";
export const UPDATE_BRAND_DATA_SUCCESS = "UPDATE_BRAND_DATA_SUCCESS";
export const UPDATE_BRAND_DATA_FAILURE = "UPDATE_BRAND_DATA_FAILURE";

export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_LOGIN_AT = "USER_LOGIN_AT";
export const USER_LOGIN_RT = "USER_LOGIN_RT";

